# Site settings
title:       Menghan Zhang · Product Designer
email:       menghan@cmu.edu
author:      Menghan Zhang
description: "Menghan Zhang's Portfolio"
baseurl:     ""
url:         ""
timezone: EST

# Google analytics
google_analytics: UA-127814315-1

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: true
github_username:
dribbble_username:
stackoverflow_id:
twitter_username:
linkedin_username:
weibo_id:
instagram_username: melodiezhang
behance_id:

# toc
toc:
  min_level: 2
  max_level: 2

# Build settings
permalink:    pretty
paginate:     5
paginate_path: "/page:num/"
sass:
  compressed: true
plugins:
  - jekyll-paginate
  - jekyll-toc
